#!/bin/bash

if [[ $# > 0 ]] 
then

VER=$1

cd docs
./make
cd ..

jq '.version = "'$VER'"' package.json > tmp.json
cat tmp.json > package.json
rm tmp.json

if [ -d dist ]
then
rm -rf dist
fi

mkdir dist

npm run dist

cd dist
rm -rf upload
mkdir upload

cp Block\ Keeper-$VER-mac.zip upload/Block-Keeper-mac.zip
cp Block\ Keeper-$VER.dmg upload/Block-Keeper.dmg
cp github/latest-mac.json upload/release.json

jq '.url = "https://github.com/DallasMcNeil/Block-Keeper/releases/download/v'$VER'/Block-Keeper-mac.zip"' < upload/release.json > tmp.json
cat tmp.json > upload/release.json
rm tmp.json

cp blockkeeper-$VER-armv7l.AppImage upload/blockkeeper-armv7l.AppImage
cp blockkeeper-$VER-i386.AppImage upload/blockkeeper-i386.AppImage
cp blockkeeper-$VER-x86_64.AppImage upload/blockkeeper-x86_64.AppImage

cp squirrel-windows-ia32/Block\ Keeper\ Setup\ $VER.exe upload/Block-Keeper-Setup.exe
cp squirrel-windows-ia32/blockkeeper-$VER-full.nupkg upload/blockkeeper-$VER-full.nupkg
cp squirrel-windows-ia32/RELEASES upload/RELEASES

cd ..

echo '{
  "win32-ia32-prod": {
    "readme": "",
    "update": "https://github.com/DallasMcNeil/Block-Keeper/releases/download/v'$VER'",
    "install": "https://github.com/DallasMcNeil/Block-Keeper/releases/download/v'$VER'/Block-Keeper-Setup.exe",
    "version": "'$VER'"
  },
  "darwin-x64-prod": {
    "readme": "",
    "update": "https://github.com/DallasMcNeil/Block-Keeper/releases/download/v'$VER'/release.json",
    "install": "https://github.com/DallasMcNeil/Block-Keeper/releases/download/v'$VER'/Block-Keeper.dmg",
    "version": "'$VER'"
  },
  "linux-ia32-prod": {
    "update": "https://github.com/DallasMcNeil/Block-Keeper/releases/download/v'$VER'/blockkeeper-i386.AppImage",
    "install": "https://github.com/DallasMcNeil/Block-Keeper/releases/download/v'$VER'/blockkeeper-i386.AppImage",
    "version": "'$VER'"
  },
  "linux-x64-prod": {
    "update": "https://github.com/DallasMcNeil/Block-Keeper/releases/download/v'$VER'/blockkeeper-x86_64.AppImage",
    "install": "https://github.com/DallasMcNeil/Block-Keeper/releases/download/v'$VER'/blockkeeper-x86_64.AppImage",
    "version": "'$VER'"
  },
  "linux-arm-prod": {
    "update": "https://github.com/DallasMcNeil/Block-Keeper/releases/download/v'$VER'/blockkeeper-armv7l.AppImage",
    "install": "https://github.com/DallasMcNeil/Block-Keeper/releases/download/v'$VER'/blockkeeper-armv7l.AppImage",
    "version": "'$VER'"
  }
}' > updates.json

cd ..

else 
  echo "ERROR: Missing version number"
fi